begin;
insert into auth.users(id,email,raw_user_meta_data) values
 ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','personal-a@example.test','{"nickname":"A"}'),
 ('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','personal-b@example.test','{"nickname":"B"}'),
 ('cccccccc-cccc-4ccc-8ccc-cccccccccccc','personal-pending@example.test','{}');
update public.qh_profiles set admission_status='approved' where id in ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb');
update public.qh_profiles set role='owner' where id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
delete from public.qh_notifications;
do $$ declare a uuid:='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';b uuid:='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';pending uuid:='cccccccc-cccc-4ccc-8ccc-cccccccccccc';p uuid;c uuid;nid uuid;r jsonb;denied boolean;cnt integer;
begin
 perform public.qh_action(a,'profile.update','{"avatar":"moon","bio":"Private bio"}');
 r:=public.qh_action(b,'profiles.get',jsonb_build_object('user_id',a));
 if r->'profile'->>'bio'<>'' or r->'profile' ? 'role' or r->'profile' ? 'status' or r->'profile' ? 'email' then raise exception 'public profile leaked private fields';end if;
 if r->'profile'->>'nickname'<>'A' or r->'profile'->>'avatar'<>'moon' then raise exception 'profile partial update destroyed nickname';end if;
 r:=public.qh_action(a,'admin.users','{}',true);
 if exists(select 1 from jsonb_array_elements(r->'users') x where x ? 'bio' or x ? 'public_bio') then raise exception 'admin users leaked private biography';end if;
 perform public.qh_action(a,'profile.update','{"public_bio":true}');
 r:=public.qh_action(b,'profiles.get',jsonb_build_object('user_id',a));
 if r->'profile'->>'bio'<>'Private bio' then raise exception 'public biography missing';end if;
 denied:=false;begin perform public.qh_action(a,'profile.update','{"avatar":"external-url"}');exception when others then denied:=sqlerrm='validation';end;
 if not denied then raise exception 'invalid avatar accepted';end if;
 denied:=false;begin perform public.qh_action(a,'profile.update','{}');exception when others then denied:=sqlerrm='validation';end;
 if not denied then raise exception 'empty profile update accepted';end if;
 denied:=false;begin perform public.qh_action(pending,'personal.overview');exception when others then denied:=sqlerrm='admission_required';end;
 if not denied then raise exception 'pending personal access';end if;
 insert into public.qh_notifications(user_id,kind,title) values(pending,'test','Cleanup');
 delete from auth.users where id=pending;
 if exists(select 1 from public.qh_notifications where user_id=pending) then raise exception 'deleted profile notifications remain';end if;
 insert into public.qh_posts(author_id,title,body,category,preference,status) values(a,'Own post','Own body','share','listen','pending') returning id into p;
 perform public.qh_action(a,'admin.moderate',jsonb_build_object('id',p,'kind','post','decision','approve','reason','Reviewed'),true);
 select count(*) into cnt from public.qh_notifications where user_id=a and kind='post_review';
 if cnt<>1 then raise exception 'post approval notification absent';end if;
 update public.qh_posts set pending_revision='{"title":"New","body":"New body","category":"share","preference":"listen"}',revision_status='draft' where id=p;
 if (select count(*) from public.qh_notifications where user_id=a)<>cnt then raise exception 'draft generated notification';end if;
 update public.qh_posts set revision_status='pending' where id=p;
 perform public.qh_action(a,'admin.moderate',jsonb_build_object('id',p,'kind','post','decision','reject','reason','Needs changes'),true);
 if (select count(*) from public.qh_notifications where user_id=a and kind='post_review')<>2 then raise exception 'revision rejection notice missing';end if;
 insert into public.qh_comments(author_id,post_id,body,status) values(b,p,'Reply','pending') returning id into c;
 perform public.qh_action(a,'admin.moderate',jsonb_build_object('id',c,'kind','comment','decision','approve','reason','Reviewed'),true);
 if not exists(select 1 from public.qh_notifications where user_id=b and kind='comment_review') or not exists(select 1 from public.qh_notifications where user_id=a and kind='received_reply') then raise exception 'reply notifications absent';end if;
 r:=public.qh_action(b,'personal.comments');
 if jsonb_array_length(r->'comments')<>1 or r->'comments'->0->>'body'<>'Reply' then raise exception 'own comments missing';end if;
 r:=public.qh_action(a,'personal.comments');if jsonb_array_length(r->'comments')<>0 then raise exception 'other comments leaked';end if;
 insert into public.qh_bookmarks(user_id,post_id) values(b,p);
 update public.qh_posts set status='hidden' where id=p;
 r:=public.qh_action(b,'personal.bookmarks');if (r->'bookmarks'->0->>'available')::boolean or r->'bookmarks'->0 ? 'body' then raise exception 'hidden bookmarked body leaked';end if;
 perform public.qh_action(b,'bookmarks.remove',jsonb_build_object('post_id',p));
 if exists(select 1 from public.qh_bookmarks where user_id=b and post_id=p) then raise exception 'unavailable bookmark removal failed';end if;
 r:=public.qh_action(b,'personal.comments');if (r->'comments'->0->>'available')::boolean or r->'comments'->0->>'post_title'='Own post' then raise exception 'hidden parent title leaked';end if;
 perform public.qh_action(a,'appeals.create',jsonb_build_object('post_id',p,'reason','Review please'));
 r:=public.qh_action(a,'personal.appeals');if jsonb_array_length(r->'appeals')<>1 or r->'appeals'->0->'content'->>'body'<>'New body' then raise exception 'own appeal content unavailable';end if;
 r:=public.qh_action(b,'personal.appeals');if jsonb_array_length(r->'appeals')<>0 then raise exception 'other appeal leaked';end if;
 select id into nid from public.qh_appeals where author_id=a;
 perform public.qh_action(a,'admin.moderate',jsonb_build_object('id',nid,'kind','appeal','decision','restore','reason','Restored after review'),true);
 r:=public.qh_action(a,'personal.appeals');
 if r->'appeals'->0->>'resolution_decision'<>'restore' or r->'appeals'->0->>'resolved_at' is null then raise exception 'appeal result detail missing';end if;
 if not exists(select 1 from public.qh_notifications where user_id=a and kind='appeal_result') then raise exception 'appeal notice missing';end if;
 select id into nid from public.qh_notifications where user_id=a limit 1;
 denied:=false;begin perform public.qh_action(b,'notifications.read',jsonb_build_object('id',nid));exception when others then denied:=sqlerrm='not_found';end;
 if not denied then raise exception 'other user notification marked read';end if;
 perform public.qh_action(a,'notifications.read',jsonb_build_object('id',nid));
 if (select read_at from public.qh_notifications where id=nid) is null then raise exception 'read not persisted';end if;
 insert into public.qh_notifications(user_id,kind,title) select a,'test','Page item '||x from generate_series(1,25) x;
 r:=public.qh_action(a,'notifications.list');if jsonb_array_length(r->'notifications')<>20 or not(r->>'hasMore')::boolean then raise exception 'notification pagination broken';end if;
 if exists(select 1 from jsonb_array_elements(r->'notifications') x where x ? 'user_id') then raise exception 'notification internal recipient exposed';end if;
 perform public.qh_action(a,'notifications.read_all');
 r:=public.qh_action(a,'notifications.list');if (r->>'unread')::integer<>0 then raise exception 'read all failed';end if;
 if not exists(select 1 from public.qh_notifications where user_id=b and read_at is null) then raise exception 'read all modified other user';end if;
 r:=public.qh_action(a,'personal.overview');if (r->'counts'->>'posts')::integer<>1 or (r->'counts'->>'unread')::integer<>0 then raise exception 'overview counts incorrect';end if;
end $$;
set local role authenticated;
do $$ declare denied boolean;begin
 denied:=false;begin perform * from public.qh_notifications;exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'browser read notifications table';end if;
 denied:=false;begin perform public.qh_action_before_personal('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','me');exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'browser executed private delegate';end if;
end $$;
reset role;
rollback;
